### ISSUE TITLE
jquery.dropotron broken

### ISSUE THREAD

**Issue by morvy** [n33/baseline#1]
I'm not sure if this is the right place for this issue, but I experience dropotron to throw errors in baseline 3.0:

`Uncaught TypeError: matchExpr[type].exec is not a function` - tested with jquery 1.11.1

it's caused by 
`Object.prototype.addEventsListener=function(t,e){var n,i=t.split(" ");for(n in i)this.addEventListener(i[n],e)}`

**Comment by yomli** [comment]
Yeah, I had the same issue : Skel Baseline 3.0 seems not to be compatible with jQuery (tested with 1.11.1 and 2.1.4).

The culprit is `main.js` which uses Polyfills. All you need to do is rewrite the file using jQuery instead :

``` javascript
(function($) {

    // Vars.
    $body = $('body');

    // Breakpoints.
    skel.breakpoints({
        xlarge: '(max-width: 1680px)',
        large:  '(max-width: 1280px)',
        medium: '(max-width: 980px)',
        small:  '(max-width: 736px)',
        xsmall: '(max-width: 480px)'
    });

    // Disable animations/transitions until everything's loaded.
    var $window = $(window),
    $body = $('body');

    $body.addClass('is-loading');

    $window.on('load', function() {
        $body.removeClass('is-loading');
    });


    // Nav.
    var $nav = $('#nav'),
    $navToggle = $('a[href="#nav"]'),
    $navClose;

        // Event: Prevent clicks/taps inside the nav from bubbling.
        $nav.on('click touchend', function(event) {
            event.stopPropagation();
        });

        // Event: Hide nav on body click/tap.
        $body.on('click touchend', function(event) {
            $nav.removeClass('visible');
        });

        // Toggle.

            // Event: Toggle nav on click.
            $navToggle.on('click', function(event) {

                event.preventDefault();
                event.stopPropagation();

                $nav.toggleClass('visible');

            });

        // Close.

            // Create element.
            $navClose = $('<a></a>');
            $navClose.attr({ href : '#', tabIndex : 0 });
            $navClose.addClass('close');
            $nav.append($navClose);

            // Event: Hide on ESC.
            $window.on('keydown', function(event) {

                if (event.keyCode == 27)
                    $nav.removeClass('visible');

            });

            // Event: Hide nav on click.
            $navClose.on('click', function(event) {

                event.preventDefault();
                event.stopPropagation();

                $nav.removeClass('visible');

            });

        })(jQuery);
```

I don't know why it uses Polyfills instead of pure vanilla javascript, so I don't want to push this quick hack.

**Comment by ajlkn** [comment]
Yep, neither of the polyfills I use (`addEventsListener` and `classList`) are necessary if you're planning to use jQuery, so you can safely drop those and use jQuery's equivalents.

As to why I'm using polyfills: `classList` isn't available on older browsers (which sucks, since it makes class manipulation far more convenient and far less kludgey than modifying the `className` property directly), and `addEventsListener` is basically just a shortcut for binding the same function to multiple events. While I could certainly have written this all w/o polyfills, a) code clarity would have suffered, and b) it'd lose the striking resemblance it has to jQuery code that made it so easy for you to port over (which was sort of my intent :)
